### ISSUE TITLE
line 180: echo: write error: Invalid argument

### ISSUE THREAD

**Issue by nmrcardoso** [liyan/suspend-usb-device#4]
Solution?:
replace line: 
    echo 'suspend' > "$POWER_LEVEL_FILE"
by
    echo "0" > "/sys/bus/usb/devices/$DEV_BUS_ID/power/autosuspend"
    echo "auto" > "/sys/bus/usb/devices/$DEV_BUS_ID/power/level"

**Comment by liyan** [comment]
This script should no longer be used on recent Linux system. Instead please use:
udisks --detach /dev/sdb

**Comment by mailinglists35** [comment]
this script STILL ROCKS, even on recent kernels with all those warnings, "udisks -detach" DOES NOT power down the drive, but the script DOES!!!

**Comment by mailinglists35** [comment]
@liyan please reopen this issue
